### ISSUE TITLE
Unable to insert xml node if it already exists in xpath

### ISSUE THREAD

**Issue by bloodmc** [Areson/xml_fragment#5]
Given the following XML 

```
  <filter>
    <filter-name>wsfilter</filter-name>
    <filter-class>com.peoplesoft.pt.events.WSFilter</filter-class>
    <async-supported>true</async-supported>
  </filter>
  <filter-mapping>
    <filter-name>wsfilter</filter-name>
    <url-pattern>/ws/*</url-pattern>
  </filter-mapping>
  <filter-mapping>
    <filter-name>wsfilter</filter-name>
    <url-pattern>/aws/*</url-pattern>
  </filter-mapping>
```

I want to modify the xml to be

```
<filter>
    <filter-name>PortalServletFilter</filter-name>
    <filter-class>com.peoplesoft.pt.custom.filter.PortalServletFilter</filter-class>
    <async-supported>true</async-supported>
  </filter>
  <filter-mapping>
    <filter-name>PortalServletFilter</filter-name>
    <url-pattern>/psp/*</url-pattern>
    <url-pattern>/psc/*</url-pattern>
    <url-pattern>/cs/*</url-pattern>
  </filter-mapping>
  <filter>
    <filter-name>wsfilter</filter-name>
    <filter-class>com.peoplesoft.pt.events.WSFilter</filter-class>
    <async-supported>true</async-supported>
  </filter>
  <filter-mapping>
    <filter-name>wsfilter</filter-name>
    <url-pattern>/ws/*</url-pattern>
  </filter-mapping>
  <filter-mapping>
    <filter-name>wsfilter</filter-name>
    <url-pattern>/aws/*</url-pattern>
  </filter-mapping>
```

When attempting to do this, xml_fragment will use the given xpath and append to it rather than create a new entry. 

Would it be possible to add a way to tell xml_fragment to create a new node even if it exists?

**Comment by alexjordan6** [comment]
Can you show us the manifest you currently have?

**Comment by bloodmc** [comment]
@alexjordan6 Here is the full xml after manual modification.
https://gist.github.com/bloodmc/9adbe076dcb9e2c6a3c4641a5b6d42ca

**Comment by bloodmc** [comment]
@alexjordan6 Any luck on the above? Thanks!

**Comment by Areson** [comment]
@alexjordan6 Super behind on things. Anyhoo, see some of your manifest to see what parameters you are using would be helpful. I think part of the issue may be that you are wanting to create new `<filter>` elements, but you have to be able to tell one apart from another, or else xml_fragment just gets confused. All the parent `<filter>` tags look the same. You might be able to try creating the parent tag with an id (if you can get away from that) so you can tell them apart, but aside from that I'm not sure what you can do. Telling it to add something under `<filter>` will do exactly that, and since a tag matching that xpath already exists, that's where it will put it.

**Comment by Areson** [comment]
Pinging this one last time. I will close this soon if I don't hear any new responses.
